// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbij4eUyO-fcFBrEpA1bwL2-nOHdc-yMQ',
    appId: '1:926223499030:android:89714545e4d33d75f59a37',
    messagingSenderId: '926223499030',
    projectId: 'ao-scan-global-companion',
    storageBucket: 'ao-scan-global-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS28a1zTFwzff1xZCzUUn0yhKq3QRvgBs',
    appId: '1:926223499030:ios:add7121450978e6cf59a37',
    messagingSenderId: '926223499030',
    projectId: 'ao-scan-global-companion',
    storageBucket: 'ao-scan-global-companion.firebasestorage.app',
    iosBundleId: 'com.aoscanglobal.aoscanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS28a1zTFwzff1xZCzUUn0yhKq3QRvgBs',
    appId: '1:926223499030:ios:32675285dd4d6131f59a37',
    messagingSenderId: '926223499030',
    projectId: 'ao-scan-global-companion',
    storageBucket: 'ao-scan-global-companion.firebasestorage.app',
    iosBundleId: 'com.example.aoScanApp',
  );

}